import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    home: 'Home',
    buy: 'Buy',
    rent: 'Rent',
    sell: 'Sell',
    agents: 'Agents',
    contact: 'Contact',
    saved: 'Saved Properties',
    myListings: 'My Listings',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    profile: 'Profile',
    language: 'Language',
    
    // Property Related
    propertyRequests: 'Property Requests',
    properties: 'Properties',
    propertyTitle: 'Property Title',
    propertyType: 'Property Type',
    propertyDetails: 'Property Details',
    allProperties: 'All Properties',
    newArrivals: 'New Arrivals',
    latestProperties: 'Latest Properties',
    noNewProperties: 'No new properties',
    noResults: 'No results found',
    viewDetails: 'View Details',
    viewAll: 'View all',
    viewMedia: 'View Media',
    fullDetails: 'Full Details',
    
    // Property Attributes
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    floors: 'Floors',
    parking: 'Parking',
    area: 'Area',
    price: 'Price',
    year: 'Year',
    beds: 'Beds',
    baths: 'Baths',
    
    // Listing Types
    forSale: 'For Sale',
    forRent: 'For Rent',
    postForSale: 'Post for Sale',
    postForRent: 'Post for Rent',
    
    // Location
    location: 'Location',
    address: 'Address',
    city: 'City',
    state: 'State/Province',
    country: 'Country',
    
    // Details & Description
    description: 'Description',
    amenities: 'Amenities',
    nearbyFacilities: 'Nearby Facilities',
    
    // Actions
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    update: 'Update',
    delete: 'Delete',
    approve: 'Approve',
    reject: 'Reject',
    search: 'Search',
    filter: 'Filter',
    applyFilter: 'Apply Filter',
    clearFilter: 'Clear Filter',
    
    // Status
    approved: 'Approved',
    rejected: 'Rejected',
    pending: 'Pending',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    failed: 'Failed',
    required: 'This field is required',
    
    // User Related
    firstName: 'First Name',
    lastName: 'Last Name',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    citizenshipNumber: 'Citizenship Number',
    profilePic: 'Profile Picture',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    
    // Forms
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterFirstName: 'Enter your first name',
    enterLastName: 'Enter your last name',
    enterPhone: 'Enter your phone',
    enterCitizenship: 'Enter your citizenship number',
    enterPrice: 'Enter price',
    enterPropertyTitle: 'Enter property title',
    enterDescription: 'Enter property description',
    enterAddress: 'Enter full address',
    selectPropertyType: 'Select property type',
    selectListingType: 'Select listing type',
    confirmPassword: 'Confirm Password',
    enterConfirmPassword: 'Re-enter password',
    passwordsDontMatch: "Passwords don't match",
    
    // Auth
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    loginRequired: 'Login required',
    logoutConfirm: 'Are you sure you want to logout?',
    
    // Media
    selectPhoto: 'Select Photo',
    selectVideo: 'Select Video',
    uploadPhoto: 'Upload Photo',
    uploadVideo: 'Upload Video',
    selectFile: 'Select File',
    clickOrDrag: 'Click or drag file to this area to upload',
    chooseFromGallery: 'Choose from Gallery',
    takePhoto: 'Take Photo',
    
    // Contact & Owner
    contactOwner: 'Contact Owner',
    contactInfo: 'Contact Info',
    ownerDetails: 'Owner Details',
    reportProperty: 'Report Property',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    agents_manage: 'Agents',
    messages: 'Messages',
    
    // Misc
    savedProperties: 'Saved Properties',
    buySellRent: 'Buy, Sell, Rent and Explore Properties in Nepal',
    quickLinks: 'Quick Links',
    company: 'Company',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    recent: 'Recent',
    popular: 'Popular',
    featured: 'Featured',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    searchPlaceholder: 'Search properties...',
    priceRange: 'Price Range',
    loadingProfile: 'Loading profile...',
    profileUpdated: 'Profile updated',
    updateFailed: 'Update failed',
    
    // Contact Page
    getInTouch: 'Get in touch',
    yourName: 'Your name',
    yourMail: 'Your mail',
    yourPhone: 'Your phone',
    yourMessage: 'Your message',
    sendMessage: 'Send message',
    sending: 'Sending...',
    feelFreeToContact: 'Feel free to contact us',
    address: 'Address',
    phone1: 'Phone 1',
    phone2: 'Phone 2',
    pleaseLoginToContact: 'Please login to contact us',
    needToBeLoggedIn: 'You need to be logged in to send us a message.',
    goToLogin: 'Go to Login',
    messageSentSuccess: 'Message sent successfully! We\'ll get back to you soon.',
    messageSendFailed: 'Failed to send message. Please try again.',
    pleaseFillAllFields: 'Please fill all fields',
    
    // Profile Page
    accountSettings: 'Account Settings',
    updatePersonalInfo: 'Update your personal information and profile picture',
    changeProfilePicture: 'Change Profile Picture',
    clickToUpload: 'Click to upload a new photo (JPG, PNG)',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    citizenshipNumber: 'Citizenship Number',
    locked: 'Locked',
    saveChanges: 'Save Changes',
    savingChanges: 'Saving Changes...',
    reset: 'Reset',
    
    // Agents Page
    ourTeam: 'OUR TEAM',
    meetOurExperts: 'Meet Our Expert Agents',
    trustedProfessionals: 'Trusted professionals ready to help you find your dream property with personalized service and expert guidance.',
    backHome: 'Back Home',
    professionalAgents: 'Professional Agent',
    professionalAgentsPlural: 'Professional Agents',
    available: 'Available',
    loadingAgents: 'Loading our amazing agents...',
    noAgentsAvailable: 'No Agents Available',
    checkBackSoon: 'Check back soon for our team of professional real estate agents.',
    realEstateAgent: 'Real Estate Agent',
    
    // PropertyDetail Page
    verified: 'Verified',
    propertyVerified: 'Property Verified',
    totalArea: 'Total area',
    builtYear: 'Built year',
    roadAccess: 'Road access',
    waterSupply: 'Water supply',
    electricitySupply: 'Electricity supply',
    ownerInfo: 'Owner Info',
    ownerName: 'Owner Name',
    ownerPhone: 'Owner Phone',
    ownerEmail: 'Owner Email',
    propertyPhotos: 'Property Photos',
    lalpurja: 'Lalpurja',
    roadPhotos: 'Road Photos',
    propertyVideos: 'Property Videos',
    roadVideos: 'Road Videos',
    reviews: 'Reviews',
    noReviews: 'No reviews yet',
    beFirstToReview: 'Be the first to review this property',
    writeReview: 'Write a Review',
    yourRating: 'Your rating',
    yourComment: 'Your comment (optional)',
    submitReview: 'Submit Review',
    submitting: 'Submitting...',
    reviewSubmitted: 'Review submitted successfully!',
    reviewFailed: 'Failed to submit review',
    
    // PropertyListPage
    propertiesFor: 'Properties for',
    sale: 'Sale',
    rentLower: 'Rent',
    filters: 'Filters',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    propertyTypeFilter: 'Property Type',
    allTypes: 'All Types',
    house: 'House',
    apartment: 'Apartment',
    land: 'Land',
    commercial: 'Commercial',
    bedroomsFilter: 'Bedrooms',
    anyBedrooms: 'Any',
    bathroomsFilter: 'Bathrooms',
    anyBathrooms: 'Any',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    sortBy: 'Sort by',
    priceLowToHigh: 'Price: Low to High',
    priceHighToLow: 'Price: High to Low',
    newest: 'Newest',
    oldest: 'Oldest',
    noPropertiesFound: 'No properties found',
    tryAdjustingFilters: 'Try adjusting your filters or search criteria',
    loadingProperties: 'Loading properties...',
    
    // Sell Page
    fillPropertyDetails: 'Fill out Property details',
    fillDetailsDescription: 'Fill details, drop a map pin for your property location, upload Lalpurja and property media. Admin will approve before it goes live.',
    propertyName: 'Property Name',
    totalArea: 'Total Area',
    constructionYear: 'Construction year',
    totalAreaAna: 'Total area (in ana)',
    postFor: 'Post for',
    areaRopani: 'Area (Ropani)',
    fillPropertyDescription: 'Fill out property description',
    pointLocation: 'Point your location on map',
    fetchNearby: 'Fetch nearby',
    selectedCoords: 'Selected',
    nearbyPlaces: 'Nearby Places',
    education: 'Education',
    food: 'Food',
    health: 'Health',
    noDataYet: 'No data yet',
    uploadMedia: 'Upload Media',
    lalpurjaUpload: 'Lalpurja Upload',
    propertyPhotoUpload: 'Property Photo Upload',
    propertyVideoUpload: 'Property Video Upload',
    roadPhotoUpload: 'Property Road Photo Upload',
    roadVideoUpload: 'Property Road Video Upload',
    uploadPropertyListing: 'Upload Property Listing',
    submittedForApproval: 'Submitted for approval. It also appears in your My Listing.',
    pleaseLoginFirst: 'Please login first.',
    pleaseDropPin: 'Please drop a pin on the map.',
    uploadFailed: 'Failed to upload',
    uploadAtLeastOne: 'Please upload at least one file (Lalpurja photo, property photo, or property video)',
    maxFilesExceeded: 'Maximum',
    filesAllowed: 'file(s) allowed for',
    fileSizeExceeded: 'The following files exceed the',
    limit: 'limit',
    compressFiles: 'Please compress or resize them before uploading.',
    clickOrDrag: 'Click or drag file to this area to upload',
    maxFileSize: 'Max file size',
    postForSell: 'Post for Sell (goes to Buy page after approval)',
    postForRent: 'Post for Rent',
    building: 'Building',
  },
  ne: {
    // Navigation
    home: 'गृह',
    buy: 'किन्नुहोस्',
    rent: 'भाडामा',
    sell: 'बेच्नुहोस्',
    agents: 'एजेन्टहरू',
    contact: 'सम्पर्क',
    saved: 'सुरक्षित सम्पत्तिहरू',
    myListings: 'मेरा सूचीहरू',
    login: 'लगइन',
    signup: 'साइन अप',
    logout: 'लगआउट',
    adminPanel: 'प्रशासक प्यानल',
    profile: 'प्रोफाइल',
    language: 'भाषा',
    
    // Property Related
    propertyRequests: 'सम्पत्ति अनुरोधहरू',
    properties: 'सम्पत्तिहरू',
    propertyTitle: 'सम्पत्ति शीर्षक',
    propertyType: 'सम्पत्तिको प्रकार',
    propertyDetails: 'सम्पत्तिको विवरण',
    allProperties: 'सबै सम्पत्तिहरू',
    newArrivals: 'नयाँ आगमन',
    latestProperties: 'नवीनतम सम्पत्तिहरू',
    noNewProperties: 'कुनै नयाँ सम्पत्ति छैन',
    noResults: 'कुनै परिणाम फेला परेन',
    viewDetails: 'विवरण हेर्नुहोस्',
    viewAll: 'सबै हेर्नुहोस्',
    viewMedia: 'मिडिया हेर्नुहोस्',
    fullDetails: 'पूर्ण विवरण',
    
    // Property Attributes
    bedrooms: 'शयनकक्षहरू',
    bathrooms: 'बाथरूमहरू',
    floors: 'तलाहरू',
    parking: 'पार्किङ',
    area: 'क्षेत्रफल',
    price: 'मूल्य',
    year: 'वर्ष',
    beds: 'शयनकक्ष',
    baths: 'बाथरूम',
    
    // Listing Types
    forSale: 'बिक्रीको लागि',
    forRent: 'भाडाको लागि',
    postForSale: 'बिक्रीको लागि पोस्ट गर्नुहोस्',
    postForRent: 'भाडाको लागि पोस्ट गर्नुहोस्',
    
    // Location
    location: 'स्थान',
    address: 'ठेगाना',
    city: 'शहर',
    state: 'राज्य/प्रान्त',
    country: 'देश',
    
    // Details & Description
    description: 'विवरण',
    amenities: 'सुविधाहरू',
    nearbyFacilities: 'नजिकैका सुविधाहरू',
    
    // Actions
    submit: 'पेश गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    save: 'सुरक्षित गर्नुहोस्',
    edit: 'सम्पादन गर्नुहोस्',
    update: 'अपडेट गर्नुहोस्',
    delete: 'मेटाउनुहोस्',
    approve: 'स्वीकृत गर्नुहोस्',
    reject: 'अस्वीकार गर्नुहोस्',
    search: 'खोज्नुहोस्',
    filter: 'फिल्टर',
    applyFilter: 'फिल्टर लागू गर्नुहोस्',
    clearFilter: 'फिल्टर खाली गर्नुहोस्',
    
    // Status
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    pending: 'विचाराधीन',
    loading: 'लोड हुँदैछ...',
    error: 'त्रुटि',
    success: 'सफलता',
    failed: 'असफल',
    required: 'यो क्षेत्र आवश्यक छ',
    
    // User Related
    firstName: 'पहिलो नाम',
    lastName: 'थर',
    name: 'नाम',
    email: 'इमेल',
    phone: 'फोन',
    citizenshipNumber: 'नागरिकता नम्बर',
    profilePic: 'प्रोफाइल तस्बिर',
    myProfile: 'मेरो प्रोफाइल',
    editProfile: 'प्रोफाइल सम्पादन गर्नुहोस्',
    changePassword: 'पासवर्ड परिवर्तन गर्नुहोस्',
    
    // Forms
    enterEmail: 'आफ्नो इमेल प्रविष्ट गर्नुहोस्',
    enterPassword: 'आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्',
    enterFirstName: 'आफ्नो पहिलो नाम प्रविष्ट गर्नुहोस्',
    enterLastName: 'आफ्नो थर प्रविष्ट गर्नुहोस्',
    enterPhone: 'आफ्नो फोन नम्बर प्रविष्ट गर्नुहोस्',
    enterCitizenship: 'आफ्नो नागरिकता नम्बर प्रविष्ट गर्नुहोस्',
    enterPrice: 'मूल्य प्रविष्ट गर्नुहोस्',
    enterPropertyTitle: 'सम्पत्तिको शीर्षक प्रविष्ट गर्नुहोस्',
    enterDescription: 'सम्पत्तिको विवरण प्रविष्ट गर्नुहोस्',
    enterAddress: 'पूरा ठेगाना प्रविष्ट गर्नुहोस्',
    selectPropertyType: 'सम्पत्तिको प्रकार चयन गर्नुहोस्',
    selectListingType: 'सूचीकरण प्रकार चयन गर्नुहोस्',
    confirmPassword: 'पासवर्ड पुष्टि गर्नुहोस्',
    enterConfirmPassword: 'पासवर्ड पुनः प्रविष्ट गर्नुहोस्',
    passwordsDontMatch: 'पासवर्डहरू मेल खाएनन्',
    
    // Auth
    dontHaveAccount: 'खाता छैन?',
    alreadyHaveAccount: 'पहिले नै खाता छ?',
    forgotPassword: 'पासवर्ड बिर्सनुभयो?',
    resetPassword: 'पासवर्ड रिसेट गर्नुहोस्',
    sendResetLink: 'रिसेट लिङ्क पठाउनुहोस्',
    backToLogin: 'लगइनमा फर्कनुहोस्',
    loginRequired: 'लगइन आवश्यक छ',
    logoutConfirm: 'के तपाईं लगआउट गर्न निश्चित हुनुहुन्छ?',
    
    // Media
    selectPhoto: 'तस्बिर चयन गर्नुहोस्',
    selectVideo: 'भिडियो चयन गर्नुहोस्',
    uploadPhoto: 'तस्बिर अपलोड गर्नुहोस्',
    uploadVideo: 'भिडियो अपलोड गर्नुहोस्',
    selectFile: 'फाइल चयन गर्नुहोस्',
    clickOrDrag: 'अपलोड गर्न यस क्षेत्रमा फाइल क्लिक वा तान्नुहोस्',
    chooseFromGallery: 'ग्यालेरीबाट छान्नुहोस्',
    takePhoto: 'तस्बिर खिच्नुहोस्',
    
    // Contact & Owner
    contactOwner: 'मालिकलाई सम्पर्क गर्नुहोस्',
    contactInfo: 'सम्पर्क जानकारी',
    ownerDetails: 'मालिकको विवरण',
    reportProperty: 'सम्पत्ति रिपोर्ट गर्नुहोस्',
    
    // Admin
    adminDashboard: 'प्रशासक ड्यासबोर्ड',
    agents_manage: 'एजेन्टहरू',
    messages: 'सन्देशहरू',
    
    // Misc
    savedProperties: 'सुरक्षित सम्पत्तिहरू',
    buySellRent: 'नेपालमा सम्पत्ति किन्नुहोस्, बेच्नुहोस्, भाडामा लिनुहोस् र अन्वेषण गर्नुहोस्',
    quickLinks: 'द्रुत लिङ्कहरू',
    company: 'कम्पनी',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा सर्तहरू',
    recent: 'हालसालै',
    popular: 'लोकप्रिय',
    featured: 'विशेष',
    yes: 'हो',
    no: 'होइन',
    ok: 'ठीक छ',
    searchPlaceholder: 'सम्पत्तिहरू खोज्नुहोस्...',
    priceRange: 'मूल्य दायरा',
    loadingProfile: 'प्रोफाइल लोड हुँदैछ...',
    profileUpdated: 'प्रोफाइल अपडेट भयो',
    updateFailed: 'अपडेट असफल भयो',
    
    // Contact Page
    getInTouch: 'सम्पर्कमा रहनुहोस्',
    yourName: 'तपाईंको नाम',
    yourMail: 'तपाईंको इमेल',
    yourPhone: 'तपाईंको फोन',
    yourMessage: 'तपाईंको सन्देश',
    sendMessage: 'सन्देश पठाउनुहोस्',
    sending: 'पठाउँदै...',
    feelFreeToContact: 'हामीलाई सम्पर्क गर्न स्वतन्त्र महसुस गर्नुहोस्',
    address: 'ठेगाना',
    phone1: 'फोन १',
    phone2: 'फोन २',
    pleaseLoginToContact: 'कृपया हामीलाई सम्पर्क गर्न लगइन गर्नुहोस्',
    needToBeLoggedIn: 'हामीलाई सन्देश पठाउन तपाईं लगइन गरिएको हुनुपर्छ।',
    goToLogin: 'लगइनमा जानुहोस्',
    messageSentSuccess: 'सन्देश सफलतापूर्वक पठाइयो! हामी चाँडै तपाईंलाई सम्पर्क गर्नेछौं।',
    messageSendFailed: 'सन्देश पठाउन असफल भयो। कृपया पुन: प्रयास गर्नुहोस्।',
    pleaseFillAllFields: 'कृपया सबै क्षेत्रहरू भर्नुहोस्',
    
    // Profile Page
    accountSettings: 'खाता सेटिङहरू',
    updatePersonalInfo: 'आफ्नो व्यक्तिगत जानकारी र प्रोफाइल तस्बिर अपडेट गर्नुहोस्',
    changeProfilePicture: 'प्रोफाइल तस्बिर परिवर्तन गर्नुहोस्',
    clickToUpload: 'नयाँ फोटो अपलोड गर्न क्लिक गर्नुहोस् (JPG, PNG)',
    emailAddress: 'इमेल ठेगाना',
    phoneNumber: 'फोन नम्बर',
    citizenshipNumber: 'नागरिकता नम्बर',
    locked: 'लक गरिएको',
    saveChanges: 'परिवर्तनहरू सुरक्षित गर्नुहोस्',
    savingChanges: 'परिवर्तनहरू सुरक्षित गर्दै...',
    reset: 'रिसेट गर्नुहोस्',
    
    // Agents Page
    ourTeam: 'हाम्रो टोली',
    meetOurExperts: 'हाम्रा विशेषज्ञ एजेन्टहरूलाई भेट्नुहोस्',
    trustedProfessionals: 'व्यक्तिगत सेवा र विशेषज्ञ मार्गदर्शनको साथ तपाईंको सपनाको सम्पत्ति फेला पार्न मद्दत गर्न तयार विश्वसनीय पेशेवरहरू।',
    backHome: 'घर फर्कनुहोस्',
    professionalAgents: 'पेशेवर एजेन्ट',
    professionalAgentsPlural: 'पेशेवर एजेन्टहरू',
    available: 'उपलब्ध',
    loadingAgents: 'हाम्रा अद्भुत एजेन्टहरू लोड गर्दै...',
    noAgentsAvailable: 'कुनै एजेन्टहरू उपलब्ध छैनन्',
    checkBackSoon: 'हाम्रो पेशेवर रियल एस्टेट एजेन्टहरूको टोलीको लागि चाँडै फर्केर जाँच गर्नुहोस्।',
    realEstateAgent: 'रियल एस्टेट एजेन्ट',
    
    // PropertyDetail Page
    verified: 'सत्यापित',
    propertyVerified: 'सम्पत्ति सत्यापित',
    totalArea: 'कुल क्षेत्रफल',
    builtYear: 'निर्माण वर्ष',
    roadAccess: 'सडक पहुँच',
    waterSupply: 'पानी आपूर्ति',
    electricitySupply: 'बिजुली आपूर्ति',
    ownerInfo: 'मालिक जानकारी',
    ownerName: 'मालिकको नाम',
    ownerPhone: 'मालिकको फोन',
    ownerEmail: 'मालिकको इमेल',
    propertyPhotos: 'सम्पत्ति फोटोहरू',
    lalpurja: 'लालपुर्जा',
    roadPhotos: 'सडक फोटोहरू',
    propertyVideos: 'सम्पत्ति भिडियोहरू',
    roadVideos: 'सडक भिडियोहरू',
    reviews: 'समीक्षाहरू',
    noReviews: 'अझै कुनै समीक्षा छैन',
    beFirstToReview: 'यो सम्पत्तिको समीक्षा गर्ने पहिलो हुनुहोस्',
    writeReview: 'समीक्षा लेख्नुहोस्',
    yourRating: 'तपाईंको मूल्याङ्कन',
    yourComment: 'तपाईंको टिप्पणी (वैकल्पिक)',
    submitReview: 'समीक्षा पेश गर्नुहोस्',
    submitting: 'पेश गर्दै...',
    reviewSubmitted: 'समीक्षा सफलतापूर्वक पेश गरियो!',
    reviewFailed: 'समीक्षा पेश गर्न असफल भयो',
    
    // PropertyListPage
    propertiesFor: 'सम्पत्तिहरू',
    sale: 'बिक्रीको लागि',
    rentLower: 'भाडाको लागि',
    filters: 'फिल्टरहरू',
    minPrice: 'न्यूनतम मूल्य',
    maxPrice: 'अधिकतम मूल्य',
    propertyTypeFilter: 'सम्पत्तिको प्रकार',
    allTypes: 'सबै प्रकार',
    house: 'घर',
    apartment: 'अपार्टमेन्ट',
    land: 'जग्गा',
    commercial: 'व्यावसायिक',
    bedroomsFilter: 'शयनकक्षहरू',
    anyBedrooms: 'कुनै पनि',
    bathroomsFilter: 'बाथरूमहरू',
    anyBathrooms: 'कुनै पनि',
    applyFilters: 'फिल्टरहरू लागू गर्नुहोस्',
    clearFilters: 'फिल्टरहरू खाली गर्नुहोस्',
    sortBy: 'क्रमबद्ध गर्नुहोस्',
    priceLowToHigh: 'मूल्य: कम देखि उच्च',
    priceHighToLow: 'मूल्य: उच्च देखि कम',
    newest: 'नवीनतम',
    oldest: 'पुरानो',
    noPropertiesFound: 'कुनै सम्पत्तिहरू फेला परेन',
    tryAdjustingFilters: 'आफ्नो फिल्टर वा खोज मापदण्ड समायोजन गर्ने प्रयास गर्नुहोस्',
    loadingProperties: 'सम्पत्तिहरू लोड गर्दै...',
    
    // Sell Page
    fillPropertyDetails: 'सम्पत्तिको विवरण भर्नुहोस्',
    fillDetailsDescription: 'विवरण भर्नुहोस्, आफ्नो सम्पत्तिको स्थानको लागि नक्सामा पिन छोड्नुहोस्, लालपुर्जा र सम्पत्ति मिडिया अपलोड गर्नुहोस्। प्रशासकले यो लाइभ हुनु अघि अनुमोदन गर्नेछ।',
    propertyName: 'सम्पत्तिको नाम',
    totalArea: 'कुल क्षेत्रफल',
    constructionYear: 'निर्माण वर्ष',
    totalAreaAna: 'कुल क्षेत्रफल (आनामा)',
    postFor: 'पोस्ट गर्नुहोस्',
    areaRopani: 'क्षेत्रफल (रोपनी)',
    fillPropertyDescription: 'सम्पत्तिको विवरण भर्नुहोस्',
    pointLocation: 'नक्सामा आफ्नो स्थान देखाउनुहोस्',
    fetchNearby: 'नजिकैको ठाउँहरू',
    selectedCoords: 'चयन गरिएको',
    nearbyPlaces: 'नजिकैका ठाउँहरू',
    education: 'शिक्षा',
    food: 'खाना',
    health: 'स्वास्थ्य',
    noDataYet: 'अझै कुनै डेटा छैन',
    uploadMedia: 'मिडिया अपलोड गर्नुहोस्',
    lalpurjaUpload: 'लालपुर्जा अपलोड',
    propertyPhotoUpload: 'सम्पत्ति फोटो अपलोड',
    propertyVideoUpload: 'सम्पत्ति भिडियो अपलोड',
    roadPhotoUpload: 'सडक फोटो अपलोड',
    roadVideoUpload: 'सडक भिडियो अपलोड',
    uploadPropertyListing: 'सम्पत्ति सूची अपलोड गर्नुहोस्',
    submittedForApproval: 'अनुमोदनको लागि पेश गरियो। यो तपाईंको मेरो सूचीमा पनि देखिन्छ।',
    pleaseLoginFirst: 'कृपया पहिले लगइन गर्नुहोस्।',
    pleaseDropPin: 'कृपया नक्सामा पिन छोड्नुहोस्।',
    uploadFailed: 'अपलोड असफल भयो',
    uploadAtLeastOne: 'कृपया कम्तिमा एउटा फाइल अपलोड गर्नुहोस् (लालपुर्जा फोटो, सम्पत्ति फोटो, वा सम्पत्ति भिडियो)',
    maxFilesExceeded: 'अधिकतम',
    filesAllowed: 'फाइल(हरू) अनुमति छ',
    fileSizeExceeded: 'निम्न फाइलहरू',
    limit: 'सीमा भन्दा बढी छन्',
    compressFiles: 'कृपया तिनीहरूलाई अपलोड गर्नु अघि कम्प्रेस वा रिसाइज गर्नुहोस्।',
    clickOrDrag: 'अपलोड गर्न यस क्षेत्रमा फाइल क्लिक वा तान्नुहोस्',
    maxFileSize: 'अधिकतम फाइल साइज',
    postForSell: 'बिक्रीको लागि पोस्ट गर्नुहोस् (अनुमोदन पछि खरिद पृष्ठमा जान्छ)',
    postForRent: 'भाडाको लागि पोस्ट गर्नुहोस्',
    building: 'भवन',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    if (language === 'ne') {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ne' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
