import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    home: 'Home',
    buy: 'Buy',
    rent: 'Rent',
    sell: 'Sell',
    agents: 'Agents',
    contact: 'Contact',
    saved: 'Saved Properties',
    myListings: 'My Listings',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    profile: 'Profile',
    language: 'Language',
    english: 'English',
    nepali: 'नेपाली',
    propertyRequests: 'Property Requests',
    properties: 'Properties',
    agents_manage: 'Agents',
    messages: 'Messages',
    fullDetails: 'Full Details',
    viewMedia: 'View Media',
    approve: 'Approve',
    reject: 'Reject',
    approved: 'Approved',
    rejected: 'Rejected',
    pending: 'Pending',
    description: 'Description',
    location: 'Location',
    propertyDetails: 'Property Details',
    amenities: 'Amenities',
    nearbyFacilities: 'Nearby Facilities',
    address: 'Address',
    city: 'City',
    state: 'State/Province',
    country: 'Country',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    floors: 'Floors',
    parking: 'Parking',
    year: 'Year',
    area: 'Area',
    price: 'Price',
    newArrivals: 'New Arrivals',
    viewAll: 'View all',
    loading: 'Loading...',
    noNewProperties: 'No new properties',
    buySellRent: 'Buy, Sell, Rent and Explore Properties in Nepal',
    beds: 'Beds',
    baths: 'Baths',
    forSale: 'For Sale',
    forRent: 'For Rent',
    allProperties: 'All Properties',
    contactInfo: 'Contact Info',
    quickLinks: 'Quick Links',
    company: 'Company',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    email: 'Email',
    phone: 'Phone',
    search: 'Search',
    filter: 'Filter',
    propertyType: 'Property Type',
    priceRange: 'Price Range',
    searchPlaceholder: 'Search properties...',
    applyFilter: 'Apply Filter',
    clearFilter: 'Clear Filter',
    noResults: 'No results found',
    clickOrDrag: 'Click or drag file to this area to upload',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone',
    citizenshipNumber: 'Citizenship Number',
    profilePic: 'Profile Picture',
    enterFirstName: 'Enter your first name',
    enterLastName: 'Enter your last name',
    enterPhone: 'Enter your phone',
    enterCitizenship: 'Enter your citizenship number',
    passwordsDontMatch: "Passwords don't match",
    confirmPassword: 'Confirm Password',
    enterConfirmPassword: 'Re-enter password',
    loadingProfile: 'Loading profile...',
    profileUpdated: 'Profile updated',
    updateFailed: 'Update failed',
    viewDetails: 'View Details',
    contactOwner: 'Contact Owner',
    reportProperty: 'Report Property',
    ownerDetails: 'Owner Details',
    name: 'Name',
    latestProperties: 'Latest Properties',
    postForSale: 'Post for Sell',
    postForRent: 'Post for Rent',
    propertyTitle: 'Property Title',
    enterPropertyTitle: 'Enter property title',
    selectPropertyType: 'Select property type',
    selectListingType: 'Select listing type',
    enterPrice: 'Enter price',
    enterDescription: 'Enter property description',
    enterAddress: 'Enter full address',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    update: 'Update',
    error: 'Error',
    success: 'Success',
    failed: 'Failed',
    required: 'This field is required',
    selectPhoto: 'Select Photo',
    selectVideo: 'Select Video',
    loginRequired: 'Login required',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    savedProperties: 'Saved Properties',
    myProfile: 'My Profile',
    adminDashboard: 'Admin Dashboard',
    recent: 'Recent',
    popular: 'Popular',
    featured: 'Featured',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    logoutConfirm: 'Are you sure you want to logout?',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    selectFile: 'Select File',
    uploadPhoto: 'Upload Photo',
    uploadVideo: 'Upload Video',
    chooseFromGallery: 'Choose from Gallery',
    takePhoto: 'Take Photo',
  },
  ne: {
    clickOrDrag: 'फाइल खोल्न वा यस क्षेत्रमा तान्नुहोस्',
    enterEmail: 'तपाइंको ईमेल प्रविष्ट गर्नुहोस्',
    enterPassword: 'तपाइंको पासवर्ड प्रविष्ट गर्नुहोस्',
    dontHaveAccount: 'खाता नाई?',
    alreadyHaveAccount: 'पहिले नै खाता छ?',
    firstName: 'पहिलो नाम',
    lastName: 'अन्तिम नाम',
    citizenshipNumber: 'नागरिकता नम्बर',
    profilePic: 'प्रोफाइल तस्बिर',
    enterFirstName: 'तपाइंको पहिलो नाम प्रविष्ट गर्नुहोस्',
    enterLastName: 'तपाइंको अन्तिम नाम प्रविष्ट गर्नुहोस्',
    enterPhone: 'तपाइंको फोन प्रविष्ट गर्नुहोस्',
    enterCitizenship: 'तपाइंको नागरिकता नम्बर प्रविष्ट गर्नुहोस्',
    passwordsDontMatch: 'पासवर्ड मेल खाएनन्',
    confirmPassword: 'पासवर्ड पुष्टि गर्नुहोस्',
    enterConfirmPassword: 'पासवर्ड पुनः प्रविष्ट गर्नुहोस्',
    loadingProfile: 'प्रोफाइल लोड हुँदैछ...',
    profileUpdated: 'प्रोफाइल अपडेट गरियो',
    updateFailed: 'अपडेट असफल',
    viewDetails: 'विवरण हेर्नुहोस्',
    contactOwner: 'मालिकसँग सम्पर्क गर्नुहोस्',
    reportProperty: 'सम्पत्ति रिपोर्ट गर्नुहोस्',
    ownerDetails: 'मालिकको विवरण',
    name: 'नाम',
    latestProperties: 'नवीनतम सम्पत्ति',
    postForSale: 'बिक्रयको लागि पोस्ट गर्नुहोस्',
    postForRent: 'भाडामा लागी पोस्ट गर्नुहोस्',
    propertyTitle: 'सम्पत्ति शीर्षक',
    enterPropertyTitle: 'सम्पत्तिको शीर्षक प्रविष्ट गर्नुहोस्',
    selectPropertyType: 'सम्पत्तिको प्रकार चयन गर्नुहोस्',
    selectListingType: 'सूचीकरण प्रकार चयन गर्नुहोस्',
    price: 'मूल्य',
    enterPrice: 'मूल्य प्रविष्ट गर्नुहोस्',
    description: 'विवरण',
    enterDescription: 'सम्पत्तिको विवरण प्रविष्ट गर्नुहोस्',
    address: 'पता',
    enterAddress: 'पूरो पता प्रविष्ट गर्नुहोस्',
    city: 'शहर',
    country: 'देश',
    bedrooms: 'शयनकक्षहरू',
    bathrooms: 'बाथरूमहरू',
    floors: 'तलाहरू',
    parking: 'पार्किङ',
    area: 'क्षेत्र',
    amenities: 'सुविधाहरू',
    nearbyFacilities: 'नजिकैको सुविधाहरू',
    submit: 'पेश गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    save: 'सुरक्षित गर्नुहोस्',
    edit: 'सम्पादन गर्नुहोस्',
    delete: 'हटाउनुहोस्',
    update: 'अपडेट गर्नुहोस्',
    loading: 'लोड हुँदैछ...',
    error: 'त्रुटि',
    success: 'सफलता',
    failed: 'असफल',
    required: 'यो क्षेत्र आवश्यक छ',
    selectPhoto: 'तस्बिर चयन गर्नुहोस्',
    selectVideo: 'भिडियो चयन गर्नुहोस्',
    noNewProperties: 'कुनै सम्पत्ति पाइएन',
    loginRequired: 'लगइन आवश्यक छ',
    forgotPassword: 'पासवर्ड बिर्सनु भयो?',
    resetPassword: 'पासवर्ड रिसेट गर्नुहोस्',
    sendResetLink: 'रिसेट लिङ्क पठाउनुहोस्',
    backToLogin: 'लगइनमा फर्क गर्नुहोस्',
    myListings: 'मेरी सूचनाहरू',
    savedProperties: 'सुरक्षित सम्पत्तिहरू',
    myProfile: 'मेरो प्रोफाइल',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    viewAll: 'सबै हेर्नुहोस्',
    recent: 'हालैको',
    popular: 'लोकप्रिय',
    featured: 'विशेष',
    approve: 'स्वीकृति दिनुहोस्',
    reject: 'अस्वीकार गर्नुहोस्',
    editProfile: 'प्रोफाइल सम्पादन गर्नुहोस्',
    changePassword: 'पासवर्ड परिवर्तन गर्नुहोस्',
    logoutConfirm: 'के तपाइं लगआउट गर्न निश्चित हुनुहुन्छ?',
    yes: 'हो',
    no: 'होइन',
    ok: 'ठीक छ',
    selectFile: 'फाइल चयन गर्नुहोस्',
    uploadPhoto: 'तस्बिर अपलोड गर्नुहोस्',
    uploadVideo: 'भिडियो अपलोड गर्नुहोस्',
    chooseFromGallery: 'ग्यालेरीबाट चयन गर्नुहोस्',
    takePhoto: 'तस्बिर लिनुहोस्',
    home: 'गृह',
    buy: 'किन्न',
    rent: 'भाडामा',
    sell: 'बेच्न',
    agents: 'एजेन्टहरू',
    contact: 'सम्पर्क',
    saved: 'सुरक्षित गुणहरू',
    login: 'लग इन',
    signup: 'साइन अप',
    logout: 'लग आउट',
    adminPanel: 'व्यवस्थापक प्यानल',
    profile: 'प्रोफाइल',
    language: 'भाषा',
    english: 'English',
    nepali: 'नेपाली',
    propertyRequests: 'सम्पत्ति अनुरोधहरू',
    properties: 'सम्पत्तिहरू',
    agents_manage: 'एजेन्टहरू',
    messages: 'सन्देशहरू',
    fullDetails: 'पूर्ण विवरणहरू',
    viewMedia: 'मिडिया हेर्नुहोस्',
    approved: 'मान्यता दिइयो',
    rejected: 'अस्वीकार गरियो',
    pending: 'लम्बित',
    description: 'विवरण',
    location: 'स्थान',
    propertyDetails: 'सम्पत्तिको विवरणहरू',
    amenities: 'सुविधाहरू',
    nearbyFacilities: 'नजिकैको सुविधाहरू',
    address: 'ठेगाना',
    city: 'शहर',
    state: 'राज्य/प्रान्त',
    country: 'देश',
    bedrooms: 'शयनकक्षहरू',
    bathrooms: 'बाथरूमहरू',
    floors: 'तलाहरू',
    parking: 'पार्किङ',
    year: 'वर्ष',
    buySellRent: 'नेपालमा सम्पत्ति किन्न, बेच्न, भाडामा लिन र अन्वेषण गर्नुहोस्',
    beds: 'शयनकक्ष',
    baths: 'बाथरूम',
    forSale: 'बिक्रयको लागि',
    forRent: 'भाडामा',
    allProperties: 'सबै सम्पत्ति',
    contactInfo: 'सम्पर्क जानकारी',
    quickLinks: 'द्रुत लिङ्कहरू',
    company: 'कम्पनी',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा शर्तहरू',
    email: 'ईमेल',
    phone: 'फोन',
    search: 'खोज्नुहोस्',
    filter: 'फिल्टर गर्नुहोस्',
    propertyType: 'सम्पत्तिको प्रकार',
    priceRange: 'मूल्य दायरा',
    searchPlaceholder: 'सम्पत्ति खोज्नुहोस्...',
    applyFilter: 'फिल्टर लागू गर्नुहोस्',
    clearFilter: 'फिल्टर खाली गर्नुहोस्',
    noResults: 'कोनो परिणाम पाइएन',
    newArrivals: 'नयाँ आगमन',
    buySellRent: 'नेपालमा सम्पत्ति किन्न, बेच्न, भाडामा लिन र अन्वेषण गर्नुहोस्',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    if (language === 'ne') {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ne' : 'en');
  };

  const t = (key) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
